### PR TITLE
babel-boilerplate

### PR DESCRIPTION
**Pull request by paulfalgout**
So I know you have issues #1 with going with the boilerplate (this is @jmeas's it was just moved to babel).  I've added it for my own benefit, but let me argue the merits in case it is at all swaying.

First off, I am not suggesting that the library be converted to ES6.  Other than the import / export which is arguably easier to understand and read than the UMD wrapper, there's really no reason to go ES6 now or quite likely ever with this library since it should reflect pre-v3 Mn.

Having the tests, test coverage, travis, etc helps ensure confidence in people to use it as a stand-alone, and the boilerplate is really just helpful for not having to manually setup all of that stuff.

The boilerplate also helps find issues like #5.

In order for this to fully work #4 and #3 (for code coverage) would need to be setup.

I also have yet to port any tests over.  But that should be a quick copy-paste and this'd be done.

### CODE REVIEW

**Comment by benmccormick** [comment]
@paulfalgout sorry this has taken so long, there was a lot to ingest with this PR, its a lot of stuff together.  I like some of it and I don't like others (the babel dependencies and renaming/styling in the source file), but I see enough value that I'm going to merge it and then work off of that to simplify.

Thanks for taking the time to contribute, sorry I've been slow to get this pulled in/respond.

**Comment by benmccormick** [comment]
@paulfalgout Take a look around after my cleanups tonight.  I think your concerns should be addressed now (though if you want complete code coverage you may want to do another PR for additional tests.  I haven't had time to see whats missing in my tests yet).  Thanks for this PR, the travis stuff in particular saved me plenty of time because I've never set that up from scratch and I would have probably wasted a lot of time figuring that stuff out.  :clap: :clap:

**Comment by paulfalgout** [comment]
Thanks for this.  I agree certain aspects are overkill.  In this case it was just easier to leave it in than pull it out.  This will certainly help my company to continue to open source some things.  We want to embrace the new patterns that v3 will provide sooner than later, but we can't abandon v2 yet either.  This helps bridge that gap.

**Comment by paulfalgout** [comment]
Everything looks good.  glad there's some tests in there.. I suppose they caught the "extends" bug?

One thing.. might not be worth changing at this point, but for that code climate code you can add that on travis-ci.  https://travis-ci.org/benmccormick/marionette-service/settings/env_vars  Kinda same difference really.

Really appreciate all the work put into this.  If you are looking to do more for any reason, feel free to open some issues or hit me up on gitter and I maybe I can help.   Thanks again :cake:

**Comment by benmccormick** [comment]
@paulfalgout Yeah thats what I ended up with for CodeClimate.  As said above, I've never done this before.  And yes the tests caught a few things that I'd rushed pulling it over here.  You really came upon this lib before it was ready for primetime :)  Hopefully now it should be usable, and thats definitely in big part thanks to you.  Thanks!

**Pull request merged**
